import { Inter, Lexend } from "next/font/google";
import "./globals.css";

const fontBody = Inter({ 
  subsets: ["latin"],
  variable: '--font-body',
});

const fontHeadline = Lexend({ 
  subsets: ["latin"],
  variable: '--font-headline',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontBody.variable} ${fontHeadline.variable}`}>
        {children}
      </body>
    </html>
  );
}
